AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  awshealthapipolling:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: s3://my-public-bucket-2020/aws-health-api-polling-ae1b9c80-aae2-44f2-9a3c-9c282db54ee3.zip
      Description: 'lambda function'
      MemorySize: 128
      Timeout: 900
      Role: 'arn:aws:iam::910003606845:role/lambda-role'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
